version: '3.4'

services:
  app:
    image: new
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
      - "5912:5912"

  redis:
    image: "redis:latest"
    ports:
      - "16379:6379"
